[program:volatile]
command=/root/VolatileCyberDefense/venv/bin/python /root/VolatileCyberDefense/app.py
autostart=true
autorestart=true
stopsignal=QUIT
stdout_logfile=/var/log/supervisor/volatile-err.log
stderr_logfile=/var/log/supervisor/volatile-err.log