apiVersion: v1
kind: ServiceAccount
metadata:
  name: vcd-sidecar

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vcd-netpol-updater
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vcd-netpol-updater-binding
subjects:
  - kind: ServiceAccount
    name: vcd-sidecar
roleRef:
  kind: Role
  name: vcd-netpol-updater
  apiGroup: rbac.authorization.k8s.io
